function [F_fw, M_fw] = pusher_forces_and_moments(u,params)

% Function to commute forces and moments contributed by the pusher motor
% FW_propulsion_data;
% Extracting appriopriate input
delta_T = u(4); % Throttle Input

% Thrust generated by pusher motor
T_pusher = interp1(params.fw.Throttle, params.fw.Thrust, delta_T, 'linear', 'extrap');
Q_pusher = interp1(params.fw.Throttle, params.fw.Torque, delta_T, 'linear', 'extrap');

% Clamp to zero to avoid negative thrust
T_pusher = max(T_pusher, 0);
Q_pusher = max(Q_pusher, 0);

F_fw = [T_pusher, 0 , 0];    
F_fw = F_fw';

% Moments generated by pusher motor
r_pusher = [0,0,0]; % pusher position


% Moment computation
M = cross(F_fw, r_pusher);

M_fw = M';% + [Q_pusher, 0, 0];

end


